export type ImportantIrregularVerb = { de: string; en: string; detail: string };

// Curated study set imported from unregelmaessige_verben_ohne_praesens.csv.
// Präsens forms were completed from the app conjugation data.
export const importantIrregularVerbs: ImportantIrregularVerb[] = [
  { de: "backen", en: "to bake", detail: "backt, backte/buk, hat gebacken" },
  { de: "befehlen", en: "to command", detail: "befiehlt, befahl, hat befohlen" },
  { de: "beginnen", en: "to begin", detail: "beginnt, begann, hat begonnen" },
  { de: "beißen", en: "to bite", detail: "beißt, biss, hat gebissen" },
  { de: "bergen", en: "to rescue / salvage", detail: "birgt, barg, hat geborgen" },
  { de: "betrügen", en: "to deceive", detail: "betrügt, betrog, hat betrogen" },
  { de: "beweisen", en: "to prove", detail: "beweist, bewies, hat bewiesen" },
  { de: "bewegen", en: "to move", detail: "bewegt, bewog, hat bewogen" },
  { de: "sich bewerben", en: "to apply", detail: "bewirbt sich, bewarb sich, hat sich beworben" },
  { de: "bewerfen", en: "to throw at", detail: "bewirft, bewarf, hat beworfen" },
  { de: "biegen", en: "to bend", detail: "biegt, bog, hat gebogen" },
  { de: "bieten", en: "to offer", detail: "bietet, bot, hat geboten" },
  { de: "binden", en: "to bind / tie", detail: "bindet, band, hat gebunden" },
  { de: "bitten", en: "to ask / request", detail: "bittet, bat, hat gebeten" },
  { de: "blasen", en: "to blow", detail: "bläst, blies, hat geblasen" },
  { de: "bleiben", en: "to stay", detail: "bleibt, blieb, ist geblieben" },
  { de: "brechen", en: "to break", detail: "bricht, brach, hat/ist gebrochen" },
  { de: "brennen", en: "to burn", detail: "brennt, brannte, hat gebrannt" },
  { de: "braten", en: "to fry / roast", detail: "brät, briet, hat gebraten" },
  { de: "bringen", en: "to bring", detail: "bringt, brachte, hat gebracht" },
  { de: "durchdringen", en: "to penetrate", detail: "durchdringt, durchdrang, ist durchgedrungen / hat durchdrungen" },
  { de: "denken", en: "to think", detail: "denkt, dachte, hat gedacht" },
  { de: "dürfen", en: "may / to be allowed", detail: "darf, durfte, hat gedurft / hat dürfen" },
  { de: "empfangen", en: "to receive", detail: "empfängt, empfing, hat empfangen" },
  { de: "empfehlen", en: "to recommend", detail: "empfiehlt, empfahl, hat empfohlen" },
  { de: "empfinden", en: "to feel / perceive", detail: "empfindet, empfand, hat empfunden" },
  { de: "entscheiden", en: "to decide", detail: "entscheidet, entschied, hat entschieden" },
  { de: "erheben", en: "to raise", detail: "erhebt, erhob, hat erhoben" },
  { de: "erklingen", en: "to sound", detail: "erklingt, erklang, ist erklungen" },
  { de: "erlöschen", en: "to expire / go out", detail: "erlischt, erlosch, ist erloschen" },
  { de: "erschrecken", en: "to be frightened", detail: "erschrickt, erschrak, ist erschrocken" },
  { de: "essen", en: "to eat", detail: "isst, aß, hat gegessen" },
  { de: "fahren", en: "to drive / travel", detail: "fährt, fuhr, ist gefahren" },
  { de: "fallen", en: "to fall", detail: "fällt, fiel, ist gefallen" },
  { de: "fangen", en: "to catch", detail: "fängt, fing, hat gefangen" },
  { de: "finden", en: "to find", detail: "findet, fand, hat gefunden" },
  { de: "fliegen", en: "to fly", detail: "fliegt, flog, ist geflogen" },
  { de: "fliehen", en: "to flee", detail: "flieht, floh, ist geflohen" },
  { de: "fließen", en: "to flow", detail: "fließt, floss, ist geflossen" },
  { de: "fressen", en: "to eat (animals)", detail: "frisst, fraß, hat gefressen" },
  { de: "frieren", en: "to freeze / feel cold", detail: "friert, fror, hat gefroren" },
  { de: "gebären", en: "to give birth", detail: "gebiert, gebar, hat geboren" },
  { de: "geben", en: "to give", detail: "gibt, gab, hat gegeben" },
  { de: "gedeihen", en: "to thrive", detail: "gedeiht, gedieh, ist gediehen" },
  { de: "gefallen", en: "to please", detail: "gefällt, gefiel, hat gefallen" },
  { de: "gehen", en: "to go", detail: "geht, ging, ist gegangen" },
  { de: "gelingen", en: "to succeed", detail: "gelingt, gelang, ist gelungen" },
  { de: "gelten", en: "to apply / be valid", detail: "gilt, galt, hat gegolten" },
  { de: "genießen", en: "to enjoy", detail: "genießt, genoss, hat genossen" },
  { de: "geschehen", en: "to happen", detail: "geschieht, geschah, ist geschehen" },
  { de: "gewinnen", en: "to win", detail: "gewinnt, gewann, hat gewonnen" },
  { de: "gießen", en: "to pour", detail: "gießt, goss, hat gegossen" },
  { de: "gleichen", en: "to resemble / equal", detail: "gleicht, glich, hat geglichen" },
  { de: "gleiten", en: "to glide", detail: "gleitet, glitt, ist geglitten" },
  { de: "graben", en: "to dig", detail: "gräbt, grub, hat gegraben" },
  { de: "greifen", en: "to grasp", detail: "greift, griff, hat gegriffen" },
  { de: "haben", en: "to have", detail: "hat, hatte, hat gehabt" },
  { de: "halten", en: "to hold / stop", detail: "hält, hielt, hat gehalten" },
  { de: "hängen", en: "to hang", detail: "hängt, hing, hat gehangen" },
  { de: "heben", en: "to lift", detail: "hebt, hob, hat gehoben" },
  { de: "heißen", en: "to be called", detail: "heißt, hieß, hat geheißen" },
  { de: "helfen", en: "to help", detail: "hilft, half, hat geholfen" },
  { de: "kennen", en: "to know / be familiar with", detail: "kennt, kannte, hat gekannt" },
  { de: "klingen", en: "to sound", detail: "klingt, klang, hat geklungen" },
  { de: "kneifen", en: "to pinch", detail: "kneift, kniff, hat gekniffen" },
  { de: "kommen", en: "to come", detail: "kommt, kam, ist gekommen" },
  { de: "können", en: "can / to be able to", detail: "kann, konnte, hat gekonnt / hat können" },
  { de: "kriechen", en: "to crawl", detail: "kriecht, kroch, ist gekrochen" },
  { de: "laden", en: "to load / charge", detail: "lädt, lud, hat geladen" },
  { de: "lassen", en: "to let / leave", detail: "läßt, ließ, hat gelassen / hat lassen" },
  { de: "laufen", en: "to run / walk", detail: "läuft, lief, ist gelaufen" },
  { de: "leiden", en: "to suffer", detail: "leidet, litt, hat gelitten" },
  { de: "leihen", en: "to lend / borrow", detail: "leiht, lieh, hat geliehen" },
  { de: "lesen", en: "to read", detail: "liest, las, hat gelesen" },
  { de: "liegen", en: "to lie / be located", detail: "liegt, lag, hat gelegen" },
  { de: "lügen", en: "to lie", detail: "lügt, log, hat gelogen" },
  { de: "meiden", en: "to avoid", detail: "meidet, mied, hat gemieden" },
  { de: "melken", en: "to milk", detail: "melkt, molk, hat gemolken" },
  { de: "messen", en: "to measure", detail: "misst, maß, hat gemessen" },
  { de: "misslingen", en: "to fail", detail: "misslingt, misslang, ist misslungen" },
  { de: "mögen", en: "to like", detail: "mag, mochte, hat gemocht" },
  { de: "müssen", en: "must / to have to", detail: "muß, musste, hat gemusst / hat müssen" },
  { de: "nehmen", en: "to take", detail: "nimmt, nahm, hat genommen" },
  { de: "nennen", en: "to name / call", detail: "nennt, nannte, hat genannt" },
  { de: "pfeifen", en: "to whistle", detail: "pfeift, pfiff, hat gepfiffen" },
  { de: "preisen", en: "to praise", detail: "preist, pries, hat gepriesen" },
];

