// Generated from german-verbs / german-verbs-dict (Apache-2.0)
export const irregularForms: Record<string, string> = {
  "herunterladen": `Präsens: lädt herunter · Präteritum: lud herunter · Perfekt: hat heruntergeladen`,
  "spazieren gehen": `Präsens: geht spazieren · Präteritum: ging spazieren · Perfekt: ist spazieren gegangen`,
  "vorhaben": `Präsens: hat vor · Präteritum: hatte vor · Perfekt: hat vorgehabt`,
  "abbrechen": `Präsens: bricht ab · Präteritum: brach ab · Perfekt: hat abgebrochen`,
  "abfahren": `Präsens: fährt ab · Präteritum: fuhr ab · Perfekt: ist abgefahren`,
  "abgeben": `Präsens: gibt ab · Präteritum: gab ab · Perfekt: hat abgegeben`,
  "abhängen": `Präsens: hängt ab · Präteritum: hängte ab · Perfekt: hat abgehangen`,
  "abheben": `Präsens: hebt ab · Präteritum: hob ab · Perfekt: hat abgehoben`,
  "abnehmen": `Präsens: nimmt ab · Präteritum: nahm ab · Perfekt: hat abgenommen`,
  "abschließen": `Präsens: schließt ab · Präteritum: schloß ab · Perfekt: hat abgeschlossen`,
  "anbieten": `Präsens: bietet an · Präteritum: bot an · Perfekt: hat angeboten`,
  "anerkennen": `Präsens: erkennt an · Präteritum: erkannte an · Perfekt: hat anerkannt`,
  "anfangen": `Präsens: fängt an · Präteritum: fing an · Perfekt: hat angefangen`,
  "angeben": `Präsens: gibt an · Präteritum: gab an · Perfekt: hat angegeben`,
  "ankommen": `Präsens: kommt an · Präteritum: kam an · Perfekt: ist angekommen`,
  "annehmen": `Präsens: nimmt an · Präteritum: nahm an · Perfekt: hat angenommen`,
  "anrufen": `Präsens: ruft an · Präteritum: rief an · Perfekt: hat angerufen`,
  "ansehen": `Präsens: sieht an · Präteritum: sah an · Perfekt: hat angesehen`,
  "ansprechen": `Präsens: spricht an · Präteritum: sprach an · Perfekt: hat angesprochen`,
  "anwenden": `Präsens: wendet an · Präteritum: wendete an · Perfekt: hat angewandt`,
  "auffallen": `Präsens: fällt auf · Präteritum: fiel auf · Perfekt: hat aufgefallen`,
  "aufgeben": `Präsens: gibt auf · Präteritum: gab auf · Perfekt: hat aufgegeben`,
  "aufheben": `Präsens: hebt auf · Präteritum: hob auf · Perfekt: hat aufgehoben`,
  "aufladen": `Präsens: lädt auf · Präteritum: lud auf · Perfekt: hat aufgeladen`,
  "aufnehmen": `Präsens: nimmt auf · Präteritum: nahm auf · Perfekt: hat aufgenommen`,
  "aufstehen": `Präsens: steht auf · Präteritum: stand auf · Perfekt: ist aufgestanden`,
  "auftreten": `Präsens: tritt auf · Präteritum: trat auf · Perfekt: hat aufgetreten`,
  "ausfallen": `Präsens: fällt aus · Präteritum: fiel aus · Perfekt: ist ausgefallen`,
  "ausgehen": `Präsens: geht aus · Präteritum: ging aus · Perfekt: ist ausgegangen`,
  "ausleihen": `Präsens: leiht aus · Präteritum: lieh aus · Perfekt: hat ausgeliehen`,
  "ausschlafen": `Präsens: schläft aus · Präteritum: schlief aus · Perfekt: hat ausgeschlafen`,
  "aussehen": `Präsens: sieht aus · Präteritum: sah aus · Perfekt: hat ausgesehen`,
  "aussprechen": `Präsens: spricht aus · Präteritum: sprach aus · Perfekt: hat ausgesprochen`,
  "aussteigen": `Präsens: steigt aus · Präteritum: stieg aus · Perfekt: ist ausgestiegen`,
  "ausweichen": `Präsens: weicht aus · Präteritum: wich aus · Perfekt: ist ausgeweicht`,
  "ausziehen": `Präsens: zieht aus · Präteritum: zog aus · Perfekt: hat ausgezogen`,
  "backen": `Präsens: backt · Präteritum: buk · Perfekt: hat gebacken`,
  "befehlen": `Präsens: befiehlt · Präteritum: befahl · Perfekt: hat befohlen`,
  "sich befinden": `Präsens: befindet sich · Präteritum: befand sich · Perfekt: hat sich befunden`,
  "beginnen": `Präsens: beginnt · Präteritum: begann · Perfekt: hat begonnen`,
  "begreifen": `Präsens: begreift · Präteritum: begriff · Perfekt: hat begriffen`,
  "behalten": `Präsens: behält · Präteritum: behielt · Perfekt: hat behalten`,
  "beibringen": `Präsens: bringt bei · Präteritum: brachte bei · Perfekt: hat beigebracht`,
  "beißen": `Präsens: beißt · Präteritum: biß · Perfekt: hat gebissen`,
  "bekommen": `Präsens: bekommt · Präteritum: bekam · Perfekt: hat bekommen`,
  "beraten": `Präsens: berät · Präteritum: beriet · Perfekt: hat beraten`,
  "beschließen": `Präsens: beschließt · Präteritum: beschloß · Perfekt: hat beschlossen`,
  "besprechen": `Präsens: bespricht · Präteritum: besprach · Perfekt: hat besprochen`,
  "bestehen": `Präsens: besteht · Präteritum: bestand · Perfekt: hat bestanden`,
  "betreffen": `Präsens: betrifft · Präteritum: betraf · Perfekt: hat betroffen`,
  "betreiben": `Präsens: betreibt · Präteritum: betrieb · Perfekt: hat betrieben`,
  "betrügen": `Präsens: betrügt · Präteritum: betrog · Perfekt: hat betrogen`,
  "sich beziehen": `Präsens: bezieht sich · Präteritum: bezog sich · Perfekt: hat sich bezogen`,
  "biegen": `Präsens: biegt · Präteritum: bog · Perfekt: hat gebogen`,
  "bieten": `Präsens: bietet · Präteritum: bot · Perfekt: hat geboten`,
  "binden": `Präsens: bindet · Präteritum: band · Perfekt: hat gebunden`,
  "bitten": `Präsens: bittet · Präteritum: bat · Perfekt: hat gebeten`,
  "bleiben": `Präsens: bleibt · Präteritum: blieb · Perfekt: ist geblieben`,
  "braten": `Präsens: brät · Präteritum: briet · Perfekt: hat gebraten`,
  "brechen": `Präsens: bricht · Präteritum: brach · Perfekt: hat gebrochen`,
  "brennen": `Präsens: brennt · Präteritum: brannte · Perfekt: hat gebrannt`,
  "bringen": `Präsens: bringt · Präteritum: brachte · Perfekt: hat gebracht`,
  "denken": `Präsens: denkt · Präteritum: dachte · Perfekt: hat gedacht`,
  "dürfen": `Präsens: darf · Präteritum: durfte · Perfekt: hat gedurft`,
  "eindringen": `Präsens: dringt ein · Präteritum: drang ein · Perfekt: ist eingedrungen`,
  "einfallen": `Präsens: fällt ein · Präteritum: fiel ein · Perfekt: ist eingefallen`,
  "eingeben": `Präsens: gibt ein · Präteritum: gab ein · Perfekt: hat eingegeben`,
  "einhalten": `Präsens: hält ein · Präteritum: hielt ein · Perfekt: hat eingehalten`,
  "einladen": `Präsens: lädt ein · Präteritum: lud ein · Perfekt: hat eingeladen`,
  "einschlafen": `Präsens: schläft ein · Präteritum: schlief ein · Perfekt: ist eingeschlafen`,
  "einschließen": `Präsens: schließt ein · Präteritum: schloß ein · Perfekt: hat eingeschlossen`,
  "einwerfen": `Präsens: wirft ein · Präteritum: warf ein · Perfekt: hat eingeworfen`,
  "einziehen": `Präsens: zieht ein · Präteritum: zog ein · Perfekt: ist eingezogen`,
  "empfangen": `Präsens: empfängt · Präteritum: empfing · Perfekt: hat empfangen`,
  "empfehlen": `Präsens: empfiehlt · Präteritum: empfahl · Perfekt: hat empfohlen`,
  "empfinden": `Präsens: empfindet · Präteritum: empfand · Perfekt: hat empfunden`,
  "enthalten": `Präsens: enthält · Präteritum: enthielt · Perfekt: hat enthalten`,
  "entlassen": `Präsens: entläßt · Präteritum: entließ · Perfekt: hat entlassen`,
  "entnehmen": `Präsens: entnimmt · Präteritum: entnahm · Perfekt: hat entnommen`,
  "entscheiden": `Präsens: entscheidet · Präteritum: entschied · Perfekt: hat entschieden`,
  "sich entschließen": `Präsens: entschließt sich · Präteritum: entschloß sich · Perfekt: hat sich entschlossen`,
  "entsprechen": `Präsens: entspricht · Präteritum: entsprach · Perfekt: hat entsprochen`,
  "entstehen": `Präsens: entsteht · Präteritum: entstand · Perfekt: ist entstanden`,
  "entwerfen": `Präsens: entwirft · Präteritum: entwarf · Perfekt: hat entworfen`,
  "erfahren": `Präsens: erfährt · Präteritum: erfuhr · Perfekt: hat erfahren`,
  "erfinden": `Präsens: erfindet · Präteritum: erfand · Perfekt: hat erfunden`,
  "sich ergeben": `Präsens: ergibt sich · Präteritum: ergab sich · Perfekt: hat sich ergeben`,
  "ergreifen": `Präsens: ergreift · Präteritum: ergriff · Perfekt: hat ergriffen`,
  "erhalten": `Präsens: erhält · Präteritum: erhielt · Perfekt: hat erhalten`,
  "erkennen": `Präsens: erkennt · Präteritum: erkannte · Perfekt: hat erkannt`,
  "erscheinen": `Präsens: erscheint · Präteritum: erschien · Perfekt: ist erschienen`,
  "ertragen": `Präsens: erträgt · Präteritum: ertrug · Perfekt: hat ertragen`,
  "sich erweisen": `Präsens: erweist sich · Präteritum: erwies sich · Perfekt: hat sich erwiesen`,
  "erwerben": `Präsens: erwirbt · Präteritum: erwarb · Perfekt: hat erworben`,
  "erziehen": `Präsens: erzieht · Präteritum: erzog · Perfekt: hat erzogen`,
  "essen": `Präsens: isst · Präteritum: aß · Perfekt: hat gegessen`,
  "fahren": `Präsens: fährt · Präteritum: fuhr · Perfekt: ist gefahren`,
  "fallen": `Präsens: fällt · Präteritum: fiel · Perfekt: ist gefallen`,
  "fangen": `Präsens: fängt · Präteritum: fing · Perfekt: hat gefangen`,
  "fernsehen": `Präsens: sieht fern · Präteritum: sah fern · Perfekt: hat ferngesehen`,
  "feststehen": `Präsens: feststeht · Präteritum: feststand · Perfekt: hat festgestanden`,
  "finden": `Präsens: findet · Präteritum: fand · Perfekt: hat gefunden`,
  "fliegen": `Präsens: fliegt · Präteritum: flog · Perfekt: ist geflogen`,
  "fliehen": `Präsens: flieht · Präteritum: floh · Perfekt: ist geflohen`,
  "fließen": `Präsens: fließt · Präteritum: floß · Perfekt: ist geflossen`,
  "fressen": `Präsens: frisst · Präteritum: fraß · Perfekt: hat gefressen`,
  "frieren": `Präsens: friert · Präteritum: fror · Perfekt: hat gefroren`,
  "geben": `Präsens: gibt · Präteritum: gab · Perfekt: hat gegeben`,
  "gefallen": `Präsens: gefällt · Präteritum: gefiel · Perfekt: hat gefallen`,
  "gehen": `Präsens: geht · Präteritum: ging · Perfekt: ist gegangen`,
  "gelingen": `Präsens: gelingt · Präteritum: gelang · Perfekt: ist gelungen`,
  "gelten": `Präsens: gilt · Präteritum: galt · Perfekt: hat gegolten`,
  "genießen": `Präsens: genießt · Präteritum: genoß · Perfekt: hat genossen`,
  "geraten": `Präsens: gerät · Präteritum: geriet · Perfekt: ist geraten`,
  "geschehen": `Präsens: geschieht · Präteritum: geschah · Perfekt: ist geschehen`,
  "gewinnen": `Präsens: gewinnt · Präteritum: gewann · Perfekt: hat gewonnen`,
  "gießen": `Präsens: gießt · Präteritum: goß · Perfekt: hat gegossen`,
  "greifen": `Präsens: greift · Präteritum: griff · Perfekt: hat gegriffen`,
  "haben": `Präsens: hat · Präteritum: hatte · Perfekt: hat gehabt`,
  "halten": `Präsens: hält · Präteritum: hielt · Perfekt: hat gehalten`,
  "hängen": `Präsens: hängt · Präteritum: hängte · Perfekt: hat gehangen`,
  "heben": `Präsens: hebt · Präteritum: hob · Perfekt: hat gehoben`,
  "heißen": `Präsens: heißt · Präteritum: hieß · Perfekt: hat geheißen`,
  "helfen": `Präsens: hilft · Präteritum: half · Perfekt: hat geholfen`,
  "hervorheben": `Präsens: hebt hervor · Präteritum: hob hervor · Perfekt: hat hervorgehoben`,
  "hinterlassen": `Präsens: hinterläßt · Präteritum: hinterließ · Perfekt: hat hinterlassen`,
  "hinweisen": `Präsens: weist hin · Präteritum: wies hin · Perfekt: hat hingewiesen`,
  "hüpfen": `Präsens: hüpft · Präteritum: hüpfte · Perfekt: hat gehüpft`,
  "kennen": `Präsens: kennt · Präteritum: kannte · Perfekt: hat gekannt`,
  "klingen": `Präsens: klingt · Präteritum: klang · Perfekt: hat geklungen`,
  "kommen": `Präsens: kommt · Präteritum: kam · Perfekt: ist gekommen`,
  "können": `Präsens: kann · Präteritum: konnte · Perfekt: hat gekonnt`,
  "laden": `Präsens: lädt · Präteritum: lud · Perfekt: hat geladen`,
  "lassen": `Präsens: läßt · Präteritum: ließ · Perfekt: hat gelassen`,
  "laufen": `Präsens: läuft · Präteritum: lief · Perfekt: ist gelaufen`,
  "leiden": `Präsens: leidet · Präteritum: litt · Perfekt: hat gelitten`,
  "leihen": `Präsens: leiht · Präteritum: lieh · Perfekt: hat geliehen`,
  "lesen": `Präsens: liest · Präteritum: las · Perfekt: hat gelesen`,
  "liegen": `Präsens: liegt · Präteritum: lag · Perfekt: hat gelegen`,
  "lügen": `Präsens: lügt · Präteritum: log · Perfekt: hat gelogen`,
  "meiden": `Präsens: meidet · Präteritum: mied · Perfekt: hat gemieden`,
  "messen": `Präsens: misst · Präteritum: maß · Perfekt: hat gemessen`,
  "missverstehen": `Präsens: missversteht · Präteritum: missverstand · Perfekt: hat missverstanden`,
  "mitbringen": `Präsens: bringt mit · Präteritum: brachte mit · Perfekt: hat mitgebracht`,
  "mitnehmen": `Präsens: nimmt mit · Präteritum: nahm mit · Perfekt: hat mitgenommen`,
  "mögen": `Präsens: mag · Präteritum: mochte · Perfekt: hat gemocht`,
  "müssen": `Präsens: muß · Präteritum: mußte · Perfekt: hat gemusst`,
  "nachgeben": `Präsens: gibt nach · Präteritum: gab nach · Perfekt: hat nachgegeben`,
  "nachlassen": `Präsens: läßt nach · Präteritum: ließ nach · Perfekt: hat nachgelassen`,
  "nachweisen": `Präsens: weist nach · Präteritum: wies nach · Perfekt: hat nachgewiesen`,
  "nehmen": `Präsens: nimmt · Präteritum: nahm · Perfekt: hat genommen`,
  "nennen": `Präsens: nennt · Präteritum: nannte · Perfekt: hat genannt`,
  "raten": `Präsens: rät · Präteritum: riet · Perfekt: hat geraten`,
  "reiben": `Präsens: reibt · Präteritum: rieb · Perfekt: hat gerieben`,
  "reiten": `Präsens: reitet · Präteritum: ritt · Perfekt: ist geritten`,
  "rennen": `Präsens: rennt · Präteritum: rannte · Perfekt: ist gerannt`,
  "riechen": `Präsens: riecht · Präteritum: roch · Perfekt: hat gerochen`,
  "rufen": `Präsens: ruft · Präteritum: rief · Perfekt: hat gerufen`,
  "scheinen": `Präsens: scheint · Präteritum: schien · Perfekt: hat geschienen`,
  "schieben": `Präsens: schiebt · Präteritum: schob · Perfekt: hat geschoben`,
  "schiefgehen": `Präsens: schiefgeht · Präteritum: schiefging · Perfekt: ist schiefgegangen`,
  "schießen": `Präsens: schießt · Präteritum: schoß · Perfekt: hat geschossen`,
  "schlafen": `Präsens: schläft · Präteritum: schlief · Perfekt: hat geschlafen`,
  "schlagen": `Präsens: schlägt · Präteritum: schlug · Perfekt: hat geschlagen`,
  "schleichen": `Präsens: schleicht · Präteritum: schlich · Perfekt: ist geschlichen`,
  "schleifen": `Präsens: schleift · Präteritum: schliff · Perfekt: hat geschleift`,
  "schließen": `Präsens: schließt · Präteritum: schloß · Perfekt: hat geschlossen`,
  "schmeißen": `Präsens: schmeißt · Präteritum: schmiß · Perfekt: hat geschmissen`,
  "schneiden": `Präsens: schneidet · Präteritum: schnitt · Perfekt: hat geschnitten`,
  "schreiben": `Präsens: schreibt · Präteritum: schrieb · Perfekt: hat geschrieben`,
  "schreien": `Präsens: schreit · Präteritum: schrie · Perfekt: hat geschrien`,
  "schweigen": `Präsens: schweigt · Präteritum: schwieg · Perfekt: hat geschwiegen`,
  "schwimmen": `Präsens: schwimmt · Präteritum: schwamm · Perfekt: ist geschwommen`,
  "sehen": `Präsens: sieht · Präteritum: sah · Perfekt: hat gesehen`,
  "sein": `Präsens: ist · Präteritum: war · Perfekt: ist gewesen`,
  "senden": `Präsens: sendet · Präteritum: sendete · Perfekt: hat gesandt`,
  "singen": `Präsens: singt · Präteritum: sang · Perfekt: hat gesungen`,
  "sinken": `Präsens: sinkt · Präteritum: sank · Perfekt: ist gesunken`,
  "sitzen": `Präsens: sitzt · Präteritum: saß · Perfekt: hat gesessen`,
  "sollen": `Präsens: soll · Präteritum: sollte · Perfekt: hat gesollt`,
  "sprechen": `Präsens: spricht · Präteritum: sprach · Perfekt: hat gesprochen`,
  "springen": `Präsens: springt · Präteritum: sprang · Perfekt: ist gesprungen`,
  "stattfinden": `Präsens: stattfindet · Präteritum: stattfand · Perfekt: hat stattgefunden`,
  "stechen": `Präsens: sticht · Präteritum: stach · Perfekt: hat gestochen`,
  "stehen": `Präsens: steht · Präteritum: stand · Perfekt: hat gestanden`,
  "stehlen": `Präsens: stiehlt · Präteritum: stahl · Perfekt: hat gestohlen`,
  "steigen": `Präsens: steigt · Präteritum: stieg · Perfekt: ist gestiegen`,
  "sterben": `Präsens: stirbt · Präteritum: starb · Perfekt: ist gestorben`,
  "stoßen": `Präsens: stößt · Präteritum: stieß · Perfekt: hat gestoßen`,
  "streichen": `Präsens: streicht · Präteritum: strich · Perfekt: hat gestrichen`,
  "streiten": `Präsens: streitet · Präteritum: stritt · Perfekt: hat gestritten`,
  "teilnehmen": `Präsens: teilnimmt · Präteritum: teilnahm · Perfekt: hat teilgenommen`,
  "tragen": `Präsens: trägt · Präteritum: trug · Perfekt: hat getragen`,
  "treffen": `Präsens: trifft · Präteritum: traf · Perfekt: hat getroffen`,
  "treiben": `Präsens: treibt · Präteritum: trieb · Perfekt: hat getrieben`,
  "treten": `Präsens: tritt · Präteritum: trat · Perfekt: ist getreten`,
  "trinken": `Präsens: trinkt · Präteritum: trank · Perfekt: hat getrunken`,
  "tun": `Präsens: tut · Präteritum: tat · Perfekt: hat getan`,
  "überlassen": `Präsens: läßt über · Präteritum: ließ über · Perfekt: hat überlassen`,
  "übernehmen": `Präsens: nimmt über · Präteritum: nahm über · Perfekt: hat übernommen`,
  "übertreffen": `Präsens: trifft über · Präteritum: traf über · Perfekt: hat übertroffen`,
  "übertreiben": `Präsens: treibt über · Präteritum: trieb über · Perfekt: hat übertrieben`,
  "überweisen": `Präsens: weist über · Präteritum: wies über · Perfekt: hat überwiesen`,
  "überwinden": `Präsens: windet über · Präteritum: wand über · Perfekt: hat überwunden`,
  "umfahren": `Präsens: umfährt · Präteritum: umfuhr · Perfekt: hat umfahren`,
  "umfahren (separable)": `Präsens: fährt um · Präteritum: fuhr um · Perfekt: ist umgefahren`,
  "umfallen": `Präsens: fällt um · Präteritum: fiel um · Perfekt: ist umgefallen`,
  "umgeben": `Präsens: gibt um · Präteritum: gab um · Perfekt: hat umgeben`,
  "umsteigen": `Präsens: steigt um · Präteritum: stieg um · Perfekt: ist umgestiegen`,
  "umziehen": `Präsens: zieht um · Präteritum: zog um · Perfekt: ist umgezogen`,
  "unterbrechen": `Präsens: bricht unter · Präteritum: brach unter · Perfekt: hat unterbrochen`,
  "unterhalten": `Präsens: hält unter · Präteritum: hielt unter · Perfekt: hat unterhalten`,
  "unterlassen": `Präsens: läßt unter · Präteritum: ließ unter · Perfekt: hat unterlassen`,
  "unternehmen": `Präsens: nimmt unter · Präteritum: nahm unter · Perfekt: hat unternommen`,
  "unterscheiden": `Präsens: scheidet unter · Präteritum: schied unter · Perfekt: hat unterschieden`,
  "unterschreiben": `Präsens: schreibt unter · Präteritum: schrieb unter · Perfekt: hat unterschrieben`,
  "unterstreichen": `Präsens: streicht unter · Präteritum: strich unter · Perfekt: hat unterstrichen`,
  "verbergen": `Präsens: verbirgt · Präteritum: verbarg · Perfekt: hat verborgen`,
  "verbieten": `Präsens: verbietet · Präteritum: verbot · Perfekt: hat verboten`,
  "verbinden": `Präsens: verbindet · Präteritum: verband · Perfekt: hat verbunden`,
  "verbrennen": `Präsens: verbrennt · Präteritum: verbrannte · Perfekt: hat verbrannt`,
  "verbringen": `Präsens: verbringt · Präteritum: verbrachte · Perfekt: hat verbracht`,
  "vergeben": `Präsens: vergibt · Präteritum: vergab · Perfekt: hat vergeben`,
  "vergessen": `Präsens: vergißt · Präteritum: vergaß · Perfekt: hat vergessen`,
  "vergleichen": `Präsens: vergleicht · Präteritum: verglich · Perfekt: hat verglichen`,
  "sich verhalten": `Präsens: verhält sich · Präteritum: verhielt sich · Perfekt: hat sich verhalten`,
  "verlassen": `Präsens: verläßt · Präteritum: verließ · Perfekt: hat verlassen`,
  "verlieren": `Präsens: verliert · Präteritum: verlor · Perfekt: hat verloren`,
  "vermeiden": `Präsens: vermeidet · Präteritum: vermied · Perfekt: hat vermieden`,
  "verraten": `Präsens: verrät · Präteritum: verriet · Perfekt: hat verraten`,
  "verschieben": `Präsens: verschiebt · Präteritum: verschob · Perfekt: hat verschoben`,
  "verschlafen": `Präsens: verschläft · Präteritum: verschlief · Perfekt: hat verschlafen`,
  "verschwinden": `Präsens: verschwindet · Präteritum: verschwand · Perfekt: ist verschwunden`,
  "versprechen": `Präsens: verspricht · Präteritum: versprach · Perfekt: hat versprochen`,
  "verstehen": `Präsens: versteht · Präteritum: verstand · Perfekt: hat verstanden`,
  "vertragen": `Präsens: verträgt · Präteritum: vertrug · Perfekt: hat vertragen`,
  "vertreiben": `Präsens: vertreibt · Präteritum: vertrieb · Perfekt: hat vertrieben`,
  "vertreten": `Präsens: vertritt · Präteritum: vertrat · Perfekt: hat vertreten`,
  "verzeihen": `Präsens: verzeiht · Präteritum: verzieh · Perfekt: hat verziehen`,
  "vorkommen": `Präsens: kommt vor · Präteritum: kam vor · Perfekt: ist vorgekommen`,
  "vorlesen": `Präsens: liest vor · Präteritum: las vor · Perfekt: hat vorgelesen`,
  "vorliegen": `Präsens: liegt vor · Präteritum: lag vor · Perfekt: hat vorgelegen`,
  "vorschlagen": `Präsens: schlägt vor · Präteritum: schlug vor · Perfekt: hat vorgeschlagen`,
  "vorschreiben": `Präsens: schreibt vor · Präteritum: schrieb vor · Perfekt: hat vorgeschrieben`,
  "vortragen": `Präsens: trägt vor · Präteritum: trug vor · Perfekt: hat vorgetragen`,
  "vorweisen": `Präsens: weist vor · Präteritum: wies vor · Perfekt: hat vorgewiesen`,
  "wachsen": `Präsens: wächst · Präteritum: wuchs · Perfekt: ist gewachsen`,
  "wahrnehmen": `Präsens: wahrnimmt · Präteritum: wahrnahm · Perfekt: hat wahrgenommen`,
  "waschen": `Präsens: wäscht · Präteritum: wusch · Perfekt: hat gewaschen`,
  "wegfallen": `Präsens: fällt weg · Präteritum: fiel weg · Perfekt: ist weggefallen`,
  "weglassen": `Präsens: läßt weg · Präteritum: ließ weg · Perfekt: hat weggelassen`,
  "weitergeben": `Präsens: gibt weiter · Präteritum: gab weiter · Perfekt: hat weitergegeben`,
  "weiterkommen": `Präsens: kommt weiter · Präteritum: kam weiter · Perfekt: ist weitergekommen`,
  "werben": `Präsens: wirbt · Präteritum: warb · Perfekt: hat geworben`,
  "werden": `Präsens: wird · Präteritum: wurde · Perfekt: ist geworden`,
  "werfen": `Präsens: wirft · Präteritum: warf · Perfekt: hat geworfen`,
  "widerrufen": `Präsens: widerruft · Präteritum: widerrief · Perfekt: hat widerrufen`,
  "widersprechen": `Präsens: widerspricht · Präteritum: widersprach · Perfekt: hat widersprochen`,
  "wiedergeben": `Präsens: gibt wieder · Präteritum: gab wieder · Perfekt: hat wiedergegeben`,
  "wiedersehen": `Präsens: sieht wieder · Präteritum: sah wieder · Perfekt: hat wiedergesehen`,
  "wiegen": `Präsens: wiegt · Präteritum: wog · Perfekt: hat gewogen`,
  "wissen": `Präsens: weiß · Präteritum: wußte · Perfekt: hat gewusst`,
  "wollen": `Präsens: will · Präteritum: wollte · Perfekt: hat gewollt`,
  "ziehen": `Präsens: zieht · Präteritum: zog · Perfekt: hat gezogen`,
  "zugeben": `Präsens: gibt zu · Präteritum: gab zu · Perfekt: hat zugegeben`,
  "zurechtfinden": `Präsens: zurechtfindet · Präteritum: zurechtfand · Perfekt: hat zurechtgefunden`,
  "zurücktreten": `Präsens: tritt zurück · Präteritum: trat zurück · Perfekt: ist zurückgetreten`,
  "zusammentreffen": `Präsens: trifft zusammen · Präteritum: traf zusammen · Perfekt: ist zusammengetroffen`,
  "zwingen": `Präsens: zwingt · Präteritum: zwang · Perfekt: hat gezwungen`,
};
